---
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bot-app
    volumes:
      - ./images:/app/images:ro
    env_file:
      - "./.env"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    tmpfs:
      - /var/lib/postgresql/data  # remove db sample data on exit
    env_file:
      - "./.env"

# volumes:
#   postgres_data:
